### ISSUE TITLE
Broken GET handler (JSON data)

### ISSUE THREAD

**Issue by valeriansaliou** [xmppo/node-xmpp-bosh#13]
Affects 0.5.X (maybe 0.6) + nodejs 0.4.7

Everything is fine using POST, but with GET:

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object #<Object> has no method 'setHeader'
    at Object.send_response (/usr/local/lib/node_modules/node-xmpp-bosh/src/response.js:72:19)
    at Object._send_no_requeue (/usr/local/lib/node_modules/node-xmpp-bosh/src/session.js:855:12)
    at Object._pop_and_send (/usr/local/lib/node_modules/node-xmpp-bosh/src/session.js:759:18)
    at Array.<anonymous> (/usr/local/lib/node_modules/node-xmpp-bosh/src/session.js:787:22)
    at EventEmitter._tickCallback (node.js:126:26)
shisp@ubuntu:~$

**Comment by valeriansaliou** [comment]
./src/response.js:72 ->  //this._res.setHeader("Content-Length", Buffer.byteLength(msg, 'utf8')); (commented) makes it work!

**Comment by dhruvbird** [comment]
Sorry, I seem to have broken this. Fixed on current master - Thanks!
