### ISSUE TITLE
error starting node-xmpp-bosh

### ISSUE THREAD

**Issue by maxguzenski** [xmppo/node-xmpp-bosh#33]
I'm try to start bosh service in many ways (from source, from npm, etc) ... and I always get this error:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'consoleAppender'
    at Object.<anonymous> (/Users/max/projetos/node-xmpp-bosh/src/log.js:7:23)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/max/projetos/node-xmpp-bosh/src/dutil.js:563:30)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)

**Comment by dhruvbird** [comment]
Sorry about the trouble. Thanks for reporting this. It seems that the log4js API changed and the dependency >=0.4.2 was fetching the latest version, the API of which is not compatible with our usage. Fixed in https://github.com/dhruvbird/node-xmpp-bosh/commit/55344945d4b918d8f0a1a7aeb327d9b9c5fe1c46

If you want to fix your local copy, just change log4js: ">=0.4.2" to log4js: "=0.4.2" in your package.json file.

**Comment by dhruvbird** [comment]
I forgot to mention - after changing the dependency, from the directory where you have the _node_modules_ directory (or the _package.json_ file) , type:

```
$> npm install .
```

This command will fetch the right version for log4js.
