### ISSUE TITLE
Cannot build node-xmpp-bosh on windows. 

### ISSUE THREAD

**Issue by geekyme** [xmppo/node-xmpp-bosh#56]
Hi there, 
i'm following a tutorial on how to build a chat system and node-xmpp-bosh was recommended as a core ingredient. I'm using a windows system 32-bit. Installed node-gyp and node-expat already. 

I tried to npm install node-xmpp-bosh and this is the error that i get:

C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat>npm i node-xmpp-bosh
npm WARN package.json application-name@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/node-xmpp-bosh
npm http 304 https://registry.npmjs.org/node-xmpp-bosh
npm http GET https://registry.npmjs.org/tav
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/ltx
npm http GET https://registry.npmjs.org/node-expat
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/dns-srv
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/eventpipe
npm http GET https://registry.npmjs.org/log4js
npm http 304 https://registry.npmjs.org/ltx
npm http 304 https://registry.npmjs.org/node-expat
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/tav
npm http 304 https://registry.npmjs.org/dns-srv
npm WARN package.json dns-srv@0.0.6 No README.md file found!
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/eventpipe
npm http 304 https://registry.npmjs.org/log4js

> node-expat@1.6.1 install C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-
> chat\node_modules\node-xmpp-bosh\node_modules\node-expat
> node-gyp rebuild

C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\node_modules\node-xmpp
-bosh\node_modules\node-expat>node "C:\Program Files\nodejs\node_modules\npm\bin
\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/async/0.1.15

> ws@0.4.22 install C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\no
> de_modules\node-xmpp-bosh\node_modules\ws
> node install.js

  node-expat.cc
[ws v0.4.22] Attempting to compile blazing fast native extensions.
..\node-expat.cc(6): fatal error C1083: Cannot open include file: 'expat.h': No
 such file or directory [C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-c
hat\node_modules\node-xmpp-bosh\node_modules\node-expat\build\node_expat.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:219:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\node_modu
les\node-xmpp-bosh\node_modules\node-expat
gyp ERR! node -v v0.8.11
gyp ERR! node-gyp -v v0.6.11
gyp ERR! not ok
[ws v0.4.22] Native code compile failed (but the module will still work):
[ws v0.4.22] The native extensions are faster, but not required.
[ws v0.4.22] On Windows, native extensions require Visual Studio and Python.
[ws v0.4.22] On Unix, native extensions require Python, make and a C++ compiler.

[ws v0.4.22] Start npm with --ws:verbose to show compilation output (if any).
npm ERR! node-expat@1.6.1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the node-expat@1.6.1 install script.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "i" "node-xmpp-bosh"
npm ERR! cwd C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat
npm ERR! node -v v0.8.11
npm ERR! npm -v 1.1.62
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\npm-debug
.log
npm ERR! not ok code 0

**Comment by dhruvbird** [comment]
There seems to be a problem installing node-expat. Try copying the built
copy of node-expat to the node_modules folder and try again.

On Sat, Oct 27, 2012 at 3:59 AM, shawnlim2010 notifications@github.comwrote:

> Hi there,
> i'm following a tutorial on how to build a chat system and node-xmpp-bosh
> was recommended as a core ingredient. I'm using a windows system 32-bit.
> Installed node-gyp and node-expat already.
> 
> I tried to npm install node-xmpp-bosh and this is the error that i get:
> 
> C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat>npm i
> node-xmpp-bosh
> npm WARN package.json application-name@0.0.1 No README.md file found!
> npm http GET https://registry.npmjs.org/node-xmpp-bosh
> npm http 304 https://registry.npmjs.org/node-xmpp-bosh
> npm http GET https://registry.npmjs.org/tav
> npm http GET https://registry.npmjs.org/node-uuid
> npm http GET https://registry.npmjs.org/ltx
> npm http GET https://registry.npmjs.org/node-expat
> npm http GET https://registry.npmjs.org/ws
> npm http GET https://registry.npmjs.org/dns-srv
> npm http GET https://registry.npmjs.org/semver
> npm http GET https://registry.npmjs.org/underscore
> npm http GET https://registry.npmjs.org/eventpipe
> npm http GET https://registry.npmjs.org/log4js
> npm http 304 https://registry.npmjs.org/ltx
> npm http 304 https://registry.npmjs.org/node-expat
> npm http 304 https://registry.npmjs.org/ws
> npm http 304 https://registry.npmjs.org/node-uuid
> npm http 304 https://registry.npmjs.org/tav
> npm http 304 https://registry.npmjs.org/dns-srv
> npm WARN package.json dns-srv@0.0.6 No README.md file found!
> npm http 304 https://registry.npmjs.org/semver
> npm http 304 https://registry.npmjs.org/underscore
> npm http 304 https://registry.npmjs.org/eventpipe
> npm http 304 https://registry.npmjs.org/log4js
> 
> node-expat@1.6.1 install
> C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-
> chat\node_modules\node-xmpp-bosh\node_modules\node-expat
> node-gyp rebuild
> 
> C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\node_modules\node-xmpp
> -bosh\node_modules\node-expat>node "C:\Program
> Files\nodejs\node_modules\npm\bin
> \node-gyp-bin....\node_modules\node-gyp\bin\node-gyp.js" rebuild
> npm http GET https://registry.npmjs.org/options
> npm http GET https://registry.npmjs.org/tinycolor
> npm http GET https://registry.npmjs.org/commander
> npm http GET https://registry.npmjs.org/async/0.1.15
> npm http 304 https://registry.npmjs.org/tinycolor
> npm http 304 https://registry.npmjs.org/options
> npm http 304 https://registry.npmjs.org/commander
> npm http 304 https://registry.npmjs.org/async/0.1.15
> 
> ws@0.4.22 install
> C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\no
> de_modules\node-xmpp-bosh\node_modules\ws
> node install.js
> 
> node-expat.cc
> [ws v0.4.22] Attempting to compile blazing fast native extensions.
> ..\node-expat.cc(6): fatal error C1083: Cannot open include file:
> 'expat.h': No
> such file or directory
> [C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-c
> 
> hat\node_modules\node-xmpp-bosh\node_modules\node-expat\build\node_expat.vcxpro
> j]
> gyp ERR! build error
> gyp ERR! stack Error:
> C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
> failed with exit code: 1
> gyp ERR! stack at ChildProcess.onExit (C:\Program
> Files\nodejs\node_modules\
> npm\node_modules\node-gyp\lib\build.js:219:23)
> gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:96:17)
> gyp ERR! stack at Process._handle.onexit (child_process.js:678:10)
> gyp ERR! System Windows_NT 6.1.7600
> gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
> les\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd
> C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\node_modu
> les\node-xmpp-bosh\node_modules\node-expat
> gyp ERR! node -v v0.8.11
> gyp ERR! node-gyp -v v0.6.11
> gyp ERR! not ok
> [ws v0.4.22] Native code compile failed (but the module will still work):
> [ws v0.4.22] The native extensions are faster, but not required.
> [ws v0.4.22] On Windows, native extensions require Visual Studio and
> Python.
> [ws v0.4.22] On Unix, native extensions require Python, make and a C++
> compiler.
> 
> [ws v0.4.22] Start npm with --ws:verbose to show compilation output (if
> any).
> npm ERR! node-expat@1.6.1 install: node-gyp rebuild
> npm ERR! cmd "/c" "node-gyp rebuild" failed with 1
> npm ERR!
> npm ERR! Failed at the node-expat@1.6.1 install script.
> npm ERR! This is most likely a problem with the node-expat package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR! npm owner ls node-expat
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! System Windows_NT 6.1.7600
> npm ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nod
> ejs\node_modules\npm\bin\npm-cli.js" "i" "node-xmpp-bosh"
> npm ERR! cwd C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat
> npm ERR! node -v v0.8.11
> npm ERR! npm -v 1.1.62
> npm ERR! code ELIFECYCLE
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!
> C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\npm-debug
> .log
> npm ERR! not ok code 0
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dhruvbird/node-xmpp-bosh/issues/56.

## 

   -Dhruv Matani.
http://dhruvbird.com/

"What's the simplest thing that could possibly work?"
-- Ward Cunningham

**Comment by geekyme** [comment]
@dhruvbird i'm not sure what you mean by 'Try copying the built
copy of node-expat to the node_modules folder and try again'. I just opened my node_modules folder and saw node-expat inside already. I did not copy it in.

**Comment by nikhil-salgaonkar** [comment]
@shawnlim2010 Install Python 2.7.3 and try again.

**Comment by geekyme** [comment]
same problem guys... 

C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat>npm install node-xmpp-
bosh
npm WARN package.json application-name@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/node-xmpp-bosh
npm http 304 https://registry.npmjs.org/node-xmpp-bosh
npm http GET https://registry.npmjs.org/ltx
npm http GET https://registry.npmjs.org/node-expat
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/tav
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/eventpipe
npm http GET https://registry.npmjs.org/dns-srv
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/log4js
npm http 304 https://registry.npmjs.org/node-expat
npm http 304 https://registry.npmjs.org/ltx
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/eventpipe
npm http 304 https://registry.npmjs.org/dns-srv
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/ws
npm WARN package.json dns-srv@0.0.6 No README.md file found!
npm http 304 https://registry.npmjs.org/log4js
npm http 304 https://registry.npmjs.org/tav

> node-expat@1.6.1 install C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-
> chat\node_modules\node-xmpp-bosh\node_modules\node-expat
> node-gyp rebuild

C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\node_modules\node-xmpp
-bosh\node_modules\node-expat>node "C:\Program Files\nodejs\node_modules\npm\bin
\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/async/0.1.15

> ws@0.4.22 install C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\no
> de_modules\node-xmpp-bosh\node_modules\ws
> node install.js

[ws v0.4.22] Attempting to compile blazing fast native extensions.
  node-expat.cc
..\node-expat.cc(6): fatal error C1083: Cannot open include file: 'expat.h': No
 such file or directory [C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-c
hat\node_modules\node-xmpp-bosh\node_modules\node-expat\build\node_expat.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:219:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\node_modu
les\node-xmpp-bosh\node_modules\node-expat
gyp ERR! node -v v0.8.11
gyp ERR! node-gyp -v v0.6.11
gyp ERR! not ok
[ws v0.4.22] Native code compile failed (but the module will still work):
[ws v0.4.22] The native extensions are faster, but not required.
[ws v0.4.22] On Windows, native extensions require Visual Studio and Python.
[ws v0.4.22] On Unix, native extensions require Python, make and a C++ compiler.

[ws v0.4.22] Start npm with --ws:verbose to show compilation output (if any).
npm ERR! node-expat@1.6.1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the node-expat@1.6.1 install script.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "node-xmpp-bosh"
npm ERR! cwd C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat
npm ERR! node -v v0.8.11
npm ERR! npm -v 1.1.62
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\shawnlim\Documents\Websites\nodeprojects\fb-chat\npm-debug
.log
npm ERR! not ok code 0

**Comment by geekyme** [comment]
not even with python 3.3.0

**Comment by dhruvbird** [comment]
@shawnlim2010 What version of all the packages (node/python/windows/npm, etc...) are you using. If you can let me know, I'll try to get my hands on a windows machine and try it myself.

**Comment by geekyme** [comment]
@dhruvbird  
ejs : "version": "0.8.3"
express : "version": "3.0.0rc5
node-expat : "version": "2.0.0"
node-gyp : "version": "0.7.1"
node-xmpp-bosh : this is the one that i'm stuck at i cant install it... 

i'm following this tutorial here so you can see where i'm trying to install my dependencies from. http://randomgoo.blogspot.sg/2011/07/adding-facebook-chat-to-your-nodejs.html

**Comment by geekyme** [comment]
i'm also using a windows 7 32bit system

**Comment by posniewski** [comment]
I'm getting the same error as @shawnlim2010.
- Windows 7 64 bit
- Python 2.5.2
- node v0.8.9
- npm 1.1.61
- MS Visual Studio 10

The error complains that expat.h doesn't exist, and then goes on to say that the native compile failed, but that's OK. However, the entire install fails. I know nothing about NPM, but perhaps something is set as "required" when it should be "optional"?

**Comment by posniewski** [comment]
Looking at package.json, I see that node-expat 1.6.1 is required. Using `npm install node-expa@1.6.1` on its own, I get the same error. So, the problem is in node-expat. This was reported here: https://github.com/astro/node-expat/issues/47 which has an integrated fix here: https://github.com/astro/node-expat/pull/48.

The current node-expat (2.0.0) installs and builds correctly on its own. Can node-xmpp-bosh use that instead?

**Comment by dhruvbird** [comment]
@posniewski Thanks for figuring out the issue. To get it working right now, you can just go ahead and change the dep. to 2.0.0 manually in the node-xmpp-bosh package.json file. We'll look into seeing if NXB is stable with node-expat 2.0.0 (it should be, and if not, will get it to that stage before the next release).

**Comment by dhruvbird** [comment]
TODO: Update node-expat to 2.0.0 and test to verify correctness, stability & performance.

**Comment by dhruvbird** [comment]
@posniewski Alternatively (for the time being), you can try downgrading node.js to v0.6.17 (since I know that master works on that version since that is the version I am currently on).

**Comment by dhruvbird** [comment]
@posniewski @shawnlim2010 I've tested current master with node-expat v2.0.0 and it seems to be working okay. The changes are on current master. Hopefully, it should be released next week or so. Thanks for the report & the resolution. Do let me know if the current master works okay on windows.

**Comment by kalpenkcs** [comment]
HI i am getting issue in windows 32 bit system.
I have installed bosh server in windows 7 32 bit system. we configure bosh server with jappix plugin in open fire.we have correctly configure all things but bosh server unable to give response it shows error like below:

TypeError: Object # has no method 'removeListeners'
at XMPPLookupService.dutil.copy.connect (C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-x
mpp-bosh\src\lookup-service.js:72:38)
at XMPPProxy.dutil.copy.connect (C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-xmpp-bosh
\src\xmpp-proxy.js:164:24)
at Object.XMPPProxyConnector.stream_add (C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-x
mpp-bosh\src\xmpp-proxy-connector.js:162:9)
at BoshEventPipe.EventPipe.emit (C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-xmpp-bosh
\node_modules\eventpipe\eventpipe.js:63:25)
at Object.StreamStore.add_stream (C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-xmpp-bos
h\src\stream.js:184:19)
at process_bosh_request (C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-xmpp-bosh\src\bos
h.js:130:35)
at bosh_request_handler (C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-xmpp-bosh\src\bos
h.js:229:9)
at C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-xmpp-bosh\src\http-server.js:69:17
at C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-xmpp-bosh\node_modules\underscore\under
score.js:754:19
at IncomingMessage. (C:\Users\kalpen\AppData\Roaming\npm\node_modules\node-xmpp-bosh\

**Comment by kalpenkcs** [comment]
we have installed node-xmpp-bosh 0.5.0 on windows system which has no methods to find removeListener method in srv.js.

issue solved by download another setup of node-xmpp-bosh from following link 
https://github.com/dhruvbird/node-xmpp-bosh

**Comment by andy-twosticks** [comment]
I don't think this has anything to do with Windows.  I'm getting the same thing on Linux (two years later...)

```
node_expat.target.mk:99: recipe for target 'Release/obj.target/node_expat/node-expat.o' failed
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
make: Leaving directory '/home/andy/Downloads/node-v6.10.2-linux-x64/node_modules/node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node-v6.10.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/lib/node-v6.10.2-linux-x64/bin/node" "/usr/local/lib/node-v6.10.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/andy/Downloads/node-v6.10.2-linux-x64/node_modules/node-expat
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/andy/Downloads/node-v6.10.2-linux-x64/package.json'
npm WARN node-v6.10.2-linux-x64 No description
npm WARN node-v6.10.2-linux-x64 No repository field.
npm WARN node-v6.10.2-linux-x64 No README data
npm WARN node-v6.10.2-linux-x64 No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/lib/node-v6.10.2-linux-x64/bin/node" "/usr/local/bin/npm" "install" "node-xmpp-bosh"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.
```

**Comment by DigitalLeaves** [comment]
Same problem here, npm informs of a vulnerability. Running npm audit fix:

```
node_expat.target.mk:99: recipe for target 'Release/obj.target/node_expat/node-expat.o' failed
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
make: Leaving directory '/var/www/html/projectname/api/prod/node_modules/xml-object-stream/node_modules/node-expat/build' 
```
