### ISSUE TITLE
Exception thrown when websocket stream gracefully closed by client

### ISSUE THREAD

**Issue by gavllew** [xmppo/node-xmpp-bosh#77]
I'm using JSJaC as a websocket client, and when I attempt to close the connection gracefully I see the following exception on the console from node-xmpp-bosh:

[2013-05-14 04:39:45.787] [WARN] [dutil.js:_real_xml_parse:248] - _real_xml_parse::Error (Error: mismatched tag) parsing XML: <dummy>/stream:stream</dummy>
[2013-05-14 04:39:45.793] [WARN] [dutil.js:_real_xml_parse:249] - Error: mismatched tag
    at SaxExpat.write (/root/git/node-xmpp-bosh/node_modules/ltx/lib/sax_expat.js:25:28)
    at exports.Parser.write (/root/git/node-xmpp-bosh/node_modules/ltx/lib/parse.js:65:17)
    at Object.exports.parse (/root/git/node-xmpp-bosh/node_modules/ltx/lib/parse.js:90:7)
    at _real_xml_parse (/root/git/node-xmpp-bosh/src/dutil.js:245:14)
    at Object.xml_parse (/root/git/node-xmpp-bosh/src/dutil.js:267:10)
    at WebSocket.<anonymous> (/root/git/node-xmpp-bosh/src/websocket.js:200:31)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/root/git/node-xmpp-bosh/node_modules/ws/lib/WebSocket.js:514:10)
    at Receiver.opcodes.1.finish (/root/git/node-xmpp-bosh/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/root/git/node-xmpp-bosh/node_modules/ws/lib/Receiver.js:378:33)
[2013-05-14 04:39:45.809] [WARN] [websocket.js:WebSocket.<anonymous>:202] - 3de0888c-8d0b-4384-a298-08a86639a182 Closing connection due to invalid packet
[2013-05-14 04:39:45.817] [INFO] [xmpp-proxy-connector.js:Object.XMPPProxyConnector.stream_terminate:192] - WEBSOCKET 3de0888c-8d0b-4384-a298-08a86639a182 stream_terminate
[2013-05-14 04:39:45.821] [INFO] [xmpp-proxy.js:XMPPProxy.dutil.copy.terminate:228] - WEBSOCKET 3de0888c-8d0b-4384-a298-08a86639a182 - terminating

**Comment by dhruvbird** [comment]
IIRC, this is expected since websocket clients send back partial XML in some (iirc first and last) messages, and nxb just assumes that every packet is well-formed-xml for simplicity.
Need to move to a sax parser to fix this.
This is expected, and as long as it isn't crashing your process, it's normal to see it.

**Comment by gavllew** [comment]
The stream open is caught as a special case, and not handed to the generic parser (as you point out, this would also not be well-formed); I figured it would be pretty trivial to catch the stream end as a special case as well, so it can clean up properly instead of throwing an exception.

**Comment by dhruvbird** [comment]
@gavllew Since it's stream end, I didn't bother. Am more than happy to accept a patch though! :)
