### ISSUE TITLE
Problem with nodejs 0.10.21

### ISSUE THREAD

**Issue by Caez83** [xmppo/node-xmpp-bosh#96]
Hello

I have a problem with the latest version of nodes.
Node-xmpp-bosh doesn't work and crash

I have this error :
/opt/node-xmpp-bosh/node_modules/eventpipe/eventpipe.js:86
                throw args[0];
                          ^
Error: accept EMFILE
    at errnoException (net.js:901:11)
    at TCP.onconnection (net.js:1159:24)

I don't have problem with nodes 0.6.14 and node-xmpp-bosh 0.7.10

**Comment by dhruvbird** [comment]
Did you run "npm install node-xmpp-bosh" or "npm install ." after upgrading node.js? If not, you should since some of the bindings are compiled bindings (node-expat, and ws for example).

**Comment by Caez83** [comment]
Yes
I've installed node and node-xmpp-bosh in a new path.
I'm downloading the binary version of nodejs and i'm installing node-xmpp-bosh with npm install node-xmpp-bosh@version after changing my export PATH and NODE_PATH 

I can launch node, but i'm unable to connect with my software to the http-bind path and after few minutes, all the nodes instances crash with the error message. 

With node 0.6.14 i don't have this problem (and i'm doing the same procedure because i'm using a new path to )
